# Generated by Django 3.1 on 2020-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ntpcusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('Remarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ntpcvisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein', models.DateTimeField()),
                ('timeout', models.DateTimeField()),
                ('subject', models.TextField()),
                ('remarks', models.TextField()),
                ('empid', models.ForeignKey(on_delete=models.SET('DEL'), to='core.ntpcusers')),
            ],
        ),
    ]
