# Generated by Django 3.1 on 2020-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200904_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ntpcusers',
            old_name='Remarks',
            new_name='location',
        ),
        migrations.AddField(
            model_name='ntpcusers',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
