# Generated by Django 3.1 on 2020-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200915_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='externalusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('vcard', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timein', models.DateTimeField()),
                ('timeout', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('externalusers', models.ForeignKey(blank=True, on_delete=models.SET('DEL'), to='core.externalusers')),
            ],
        ),
        migrations.AlterField(
            model_name='ntpcusers',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='ntpcvisitors',
        ),
        migrations.AddField(
            model_name='visitor',
            name='ntpcusers',
            field=models.ForeignKey(blank=True, on_delete=models.SET('DEL'), to='core.ntpcusers'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='visitor',
            field=models.ForeignKey(on_delete=models.SET('DEL'), to='core.visitor'),
        ),
    ]
