# Generated by Django 3.1 on 2020-09-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200916_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='externalusers',
            new_name='externaluser',
        ),
        migrations.RenameModel(
            old_name='ntpcusers',
            new_name='ntpcuser',
        ),
    ]
