# Generated by Django 3.1 on 2020-09-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200916_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='externaluser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.externaluser'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ntpcuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ntpcuser'),
        ),
    ]
